CREATE TABLE ATHLETES(id INT IDENTITY NOT NULL, email VARCHAR(50), password VARCHAR(50), status VARCHAR, PRIMARY KEY (id))
CREATE TABLE COACHS(id INT IDENTITY NOT NULL, email VARCHAR(50), password VARCHAR(50), status VARCHAR, PRIMARY KEY (id))
CREATE TABLE TRAININGS(id INT IDENTITY NOT NULL, date DATE, PRIMARY KEY (id))
